### ISSUE TITLE
Vertical progress indicator example

### ISSUE THREAD

**Issue by mrj365** [FreshVine/Responsive-Step-Progress-Indicator#1]
I don't see a code example of the vertical progress indicator and I'm not sure how to implement it. Can you please provide an example?

**Comment by brasileric** [comment]
For me the same: I see nice examples in the images in the readme, but not clear how to make the indicator vertical.

**Comment by paulprins** [comment]
Weird, I'll dive into it and get the code/example updated soon.

**Comment by paulprins** [comment]
Found it. To use it as a vertical list you simple comment out the media query. I'll update the project with some better documentation around this.

**Comment by paulprins** [comment]
Also just added the class `.Vertical` to the css/saas and updated the sample script. You would simply add it too the `ul` node.

**Example:**  

```
<ul class="SteppedProgress Vertical">
    <li class="complete"><span>Step 1</span></li>
    <li class="complete"><span>Step 2</span></li>
    <li class="complete"><span>Step 3</span></li>
    <li class="complete"><span>Step 4</span></li>
    <li class="complete"><span>Step 5</span></li>
    <li class=""><span>Step 6</span></li>
</ul>
```

See the [commit here](https://github.com/FreshVine/Responsive-Step-Progress-Indicator/commit/ec3c14799652863116f434e47582b549788a4dc7)
